### ISSUE TITLE
Stack delete fails with `stack_status variable not found.`

### ISSUE THREAD

**Issue by kunday** [realestate-com-au/stackup#9]
Logs:

```ruby

/var/lib/gems/2.2.0/gems/stackup-0.0.7/lib/stackup/stack.rb:88:in `block in wait_for_events': undefined local variable or method `stack_status' for #<Stackup:
:Stack:0x00000001670bc8> (NameError)
        from /var/lib/gems/2.2.0/gems/stackup-0.0.7/lib/stackup/stack.rb:86:in `loop'
        from /var/lib/gems/2.2.0/gems/stackup-0.0.7/lib/stackup/stack.rb:86:in `wait_for_events'
        from /var/lib/gems/2.2.0/gems/stackup-0.0.7/lib/stackup/stack.rb:46:in `delete'
        from /vagrant/rea/cbde/jinkun/lib/jinkun/stack/master.rb:19:in `delete'


```

**Comment by kunday** [comment]
Fails for CREATE_IN_PROGRESS too:

```ruby

[11:37:35] jinkun-akunday-dev - CREATE_IN_PROGRESS - User Initiated
/var/lib/gems/2.2.0/gems/stackup-0.0.7/lib/stackup/stack.rb:88:in `block in wait_for_events': undefined local variable or method `stack_status' for #<Stackup:
:Stack:0x000000028d86d0> (NameError)

```

**Comment by kunday** [comment]
Bug was introduced in version 0.0.7.

**Comment by mdub** [comment]
Delete works now.
